// flags
// 0b001: noun -> 0, verb -> 1
// 0b010: 3.tekil yok -> 0, 3.tekil var -> 1

export const words = {
    "absürt": { local: "saçma", flags: 0b00 },
    "adisyon": { local: "hesap fiş", flags: 0b10 },
    "ambiyans": { local: "ortam", flags: 0b00 },
    "analiz": { local: "çözümleme", flags: 0b00 },
    "antipatik": { local: "sevimsiz", flags: 0b00 },
    "bodyguard": { local: "koruma", flags: 0b00 },
    "brifing": { local: "özetleme", flags: 0b00 },
    "bye": { local: "hoşça kal", flags: 0b00 },
    "bye bye": { local: "güle güle", flags: 0b00 },
    "catering": { local: "yemek hizmet", flags: 0b10 },
    "center": { local: "merkez", flags: 0b00 },
    "counter": { local: "sayaç", flags: 0b00 },
    "cv": { local: "özgeçmiş", flags: 0b00 },
    "cool": { local: "havalı", flags: 0b00 },
    "data": { local: "veri", flags: 0b00 },
    "departman": { local: "bölüm", flags: 0b00 },
    "default": { local: "varsayılan", flags: 0b00 },
    "dizayn": { local: "tasarım", flags: 0b00 },
    "döküman": { local: "belge", flags: 0b00 },
    "driver": { local: "sürücü", flags: 0b00 },
    "e-mail": { local: "e-posta", flags: 0b00 },
    "emergency": { local: "acil", flags: 0b00 },
    "ekstra": { local: "fazladan", flags: 0b00 },
    "exit": { local: "çıkış", flags: 0b00 },
    "feedback": { local: "geri bildirim", flags: 0b00 },
    "full": { local: "dolu", flags: 0b00 },
    "full time": { local: "tam gün", flags: 0b00 },
    "global": { local: "küresel", flags: 0b00 },
    "illegal": { local: "yasa dış", flags: 0b10 },
    "imitasyon": { local: "taklit", flags: 0b00 },
    "irregular": { local: "düzensiz", flags: 0b00 },
    "izolasyon": { local: "yalıtım", flags: 0b00 },
    "jenerasyon": { local: "nesil", flags: 0b00 },
    "klasifikasyon": { local: "sınıflandırma", flags: 0b00 },
    "kompleks": { local: "karmaşık", flags: 0b00 },
    "komünikasyon": { local: "iletişim", flags: 0b00 },
    "konsensus": { local: "uzlaşma", flags: 0b00 },
    "kreatif": { local: "yaratıcı", flags: 0b00 },
    "kriter": { local: "ölçüt", flags: 0b00 },
    "laptop": { local: "dizüstü bilgisayar", flags: 0b00 },
    "link": { local: "bağlantı", flags: 0b00 },
    "mantalite": { local: "anlayış", flags: 0b00 },
    "monoton": { local: "tekdüze", flags: 0b00 },
    "nick name": { local: "kullanıcı ad", flags: 0b10 },
    "objektif": { local: "nesnel", flags: 0b00 },
    "offline": { local: "çevrim dış", flags: 0b10 },
    "okey": { local: "tamam", flags: 0b00 },
    "online": { local: "çevrim içi", flags: 0b00 },
    "opsiyonel": { local: "seçmeli", flags: 0b00 },
    "optimist": { local: "iyimser", flags: 0b00 },
    "orijinal": { local: "özgün", flags: 0b00 },
    "orjinal": { local: "özgün", flags: 0b00 },
    "part time": { local: "yarı zamanlı", flags: 0b00 },
    "partikül": { local: "parçacık", flags: 0b00 },
    "perspektif": { local: "bakış açı", flags: 0b10 },
    "pesimist": { local: "kötümser", flags: 0b00 },
    "pozisyon": { local: "durum", flags: 0b00 },
    "prestij": { local: "saygınlık", flags: 0b00 },
    "prezentasyon": { local: "sunum", flags: 0b00 },
    "printer": { local: "yazıcı", flags: 0b00 },
    "print out": { local: "çıktı", flags: 0b00 },
    "randıman": { local: "verim", flags: 0b00 },
    "reaksiyon": { local: "tepkime", flags: 0b00 },
    "recycling": { local: "geri dönüşüm", flags: 0b00 },
    "security": { local: "güvenlik", flags: 0b00 },
    "sempatik": { local: "sevimli", flags: 0b00 },
    "spontane": { local: "kendiliğinden", flags: 0b00 },
    "star": { local: "yıldız", flags: 0b00 },
    "straplez": { local: "askısız giysi", flags: 0b00 },
    "subjektif": { local: "öznel", flags: 0b00 },
    "trend": { local: "moda", flags: 0b00 },
    "web": { local: "ağ", flags: 0b00 },
    "adapte ol": { local: "uyum sağla", flags: 0b01 },
    "analiz et": { local: "çözümle", flags: 0b01 },
    "anons et": { local: "duyur", flags: 0b01 },
    "brifing yap": { local: "özetle", flags: 0b01 },
    "deklare et": { local: "bildir", flags: 0b01 },
    "dizayn et": { local: "tasarla", flags: 0b01 },
    "download et": { local: "indir", flags: 0b01 },
    "elimine et": { local: "ele", flags: 0b01 },
    "empoze et": { local: "dayat", flags: 0b01 },
    "entegre ol": { local: "bütünleş", flags: 0b01 },
    "okeyle": { local: "onayla", flags: 0b01 },
    "provoke et": { local: "kışkırt", flags: 0b01 },
    "relaks ol": { local: "rahatla", flags: 0b01 },
    "revize et": { local: "yenile", flags: 0b01 },
    "save et": { local: "kaydet", flags: 0b01 },
    "start al": { local: "başla", flags: 0b01 }
};


export const twoWords={
    adapte: 'ol',
    analiz: 'et',
    anons: 'et',
    brifing: 'yap',
    deklare: 'et',
    dizayn: 'et',
    download: 'et',
    elimine: 'et',
    empoze: 'et',
    entegre: 'ol',
    provoke: 'et',
    relaks: 'ol',
    revize: 'et',
    save: 'et',
    start: 'al',
    bye: 'bye',
    full: 'time',
    nick: 'name',
    part: 'time',
}