const nouns = {
    "absürt": "saçma",
    "adisyon": "hesap fişi",
    "ambiyans": "ortam",
    "analiz": "çözümleme",
    "antipatik": "sevimsiz",
    "bodyguard": "koruma",
    "brifing": "özetleme",
    "bye": "hoşça kal",
    "bye bye": "güle güle",
    "catering": "yemek hizmeti",
    "center": "merkez",
    "counter": "sayaç",
    "cv": "özgeçmiş",
    "cool": "havalı",
    "data": "veri",
    "departman": "bölüm",
    "default" : "varsayılan",
    "dizayn": "tasarım",
    "döküman": "belge",
    "driver": "sürücü",
    "e-mail": "e-posta",
    "emergency": "acil",
    "ekstra": "fazladan",
    "exit": "çıkış",
    "feedback": "geri bildirim",
    "full": "dolu",
    "full time": "tam gün",
    "global": "küresel",
    "illegal": "yasa dışı",
    "imitasyon": "taklit",
    "irregular": "düzensiz",
    "izolasyon": "yalıtım",
    "jenerasyon": "nesil",
    "klasifikasyon": "sınıflandırma",
    "kompleks": "karmaşık",
    "komünikasyon": "iletişim",
    "konsensus": "uzlaşma",
    "kreatif": "yaratıcı",
    "kriter": "ölçüt",
    "laptop": "dizüstü bilgisayar",
    "link": "bağlantı",
    "mantalite": "anlayış",
    "monoton": "tekdüze",
    "nick name": "kullanıcı adı",
    "objektif": "nesnel",
    "offline": "çevrim dışı",
    "okey": "tamam",
    "online": "çevrim içi",
    "opsiyonel": "seçmeli",
    "optimist": "iyimser",
    "orijinal" : "özgün",
    "orjinal" : "özgün",
    "part time": "yarı zamanlı",
    "partikül": "parçacık",
    "perspektif": "bakış açısı",
    "pesimist": "kötümser",
    "pozisyon": "durum",
    "prestij": "saygınlık",
    "prezentasyon": "sunum",
    "printer": "yazıcı",
    "print out": "çıktı",
    "randıman": "verim",
    "reaksiyon": "tepkime",
    "recycling": "geri dönüşüm",
    "security": "güvenlik",
    "sempatik": "sevimli",
    "spontane": "kendiliğinden",
    "star": "yıldız",
    "straplez": "askısız giysi",
    "subjektif": "öznel",
    "transfer": "nakil",
    "trend": "moda",
    "web" : "ağ",
};

const verbs = {
    "adapte ol": "uyum sağla",
    "analiz et": "çözümle",
    "anons et": "duyur",
    "brifing yap": "özetle",
    "deklare et": "bildir",
    "dizayn et": "tasarla",
    "download et": "indir",
    "elimine et": "ele",
    "empoze et": "dayat",
    "entegre ol": "bütünleş",
    "okeyle": "onayla",
    "provoke et": "kışkırt",
    "relaks ol": "rahatla",
    "revize et": "yenile",
    "save et": "kaydet",
    "start al": "başla",
    "transfer et": "naklet",
};

const twoWords={
    adapte: 'ol',
    analiz: 'et',
    anons: 'et',
    deklare: 'et',
    dizayn: 'et',
    download: 'et',
    elimine: 'et',
    empoze: 'et',
    entegre: 'ol',
    provoke: 'et',
    relaks: 'ol',
    revize: 'et',
    save: 'et',
    start: 'al',
    transfer: 'et',
    bye: 'bye',
    full: 'time',
    nick: 'name',
    part: 'time',
}